// src/constants/action-types.js

export const CREATE_STRUCTURE = 'CREATE_STRUCTURE';
export const FOUND_BAD_WORD = 'FOUND_BAD_WORD';
export const LOAD_STRUCTURES = 'LOAD_STRUCTURES';
export const LOAD_MACHINES = 'LOAD_MACHINES';
export const LOAD_MACHINE_TYPES = 'LOAD_MACHINE_TYPES';
export const CREATE_MACHINE = 'CREATE_MACHINE';
export const CREATE_SENSOR = 'CREATE SENSOR';
export const DISPLAY_STRUCTURE = 'DISPLAY_STRUCTURE';
export const DELETE_STRUCTURE = 'DELETE_STRUCTURE';
export const CLEAR_DATA = 'CLEAR_DATA';
export const DISPLAY_MACHINE = 'DISPLAY_MACHINE';
export const SET_AUTHORIZED = 'SET_AUTHORIZED';
export const DISPLAY_SENSOR = 'DISPLAY_SENSOR';
export const LOAD_SENSORS = 'LOAD_SENSORS';
export const LOAD_INDIVIDUAL_MACHINE = 'LOAD_INDIVIDUAL_MACHINE';
export const DELETE_MACHINE = 'DELETE_MACHINE';
